#!/bin/bash

# Written by Nicolas Bigaouette
# nbigaouette@gmail.com
# June 2012
# v0.2
# http://stackoverflow.com/questions/1887364/git-clone-to-external-drive-for-backup

. git_repos.conf
. backup_git_repos_functions.sh


log "Starting backing up git repos on `date`"                                   2>&1 | tee -a ${logfile}
backup_all_repos
log "Done backing up git repos on `date`"                                       2>&1 | tee -a ${logfile}
send_log_to_servers

